# Generated by Django 6.0.6 on 2026-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_booking_is_verified_booking_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available',
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_reference',
            field=models.CharField(blank=True, help_text="Customer-entered eSewa reference, used when the automatic eSewa redirect isn't reachable. Check this against your own eSewa transaction history before verifying the booking.", max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('auto', 'Automatic (eSewa redirect)'), ('manual', 'Manual (customer-reported reference)')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Untick to hide this vehicle from the site entirely (e.g. sold, retired, under repair). This is independent of bookings — do NOT use this to mark a vehicle as booked; that happens automatically once a customer's booking is confirmed."),
        ),
    ]
