# Generated by Django 6.0 on 2026-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicles",
            "0003_remove_vehicle_is_available_payment_manual_reference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="destination",
        ),
        migrations.AddField(
            model_name="booking",
            name="with_driver",
            field=models.BooleanField(
                default=False,
                help_text="True if the customer chose to book with a driver, False for self-drive",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver_cost_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=1500,
                help_text="Extra cost per day if the customer books this vehicle with a driver",
                max_digits=10,
            ),
        ),
    ]
